### ISSUE TITLE
Incorrect brightnessctl command results in loss of brightness output

### ISSUE THREAD

**Issue by ferroson** [owl4ce/dotfiles#197] opened 2022-09-10 16:06 UTC
**Describe the bug**
The brightnessctl command used is incorrect so it is not recognized, this causes a loss of brightness output, the bug is in line 47 of ~/.config/rofi/scripts/custom-modi/modi-media.sh

**Expected behavior**
Output brightness should not be lost

**Screenshots**
This is the terminal output of $brightnessctl get -P and $brightnessctl get (without -P):
![2022-09-10-223219_1366x768_scrot](https://user-images.githubusercontent.com/108534456/189491440-679335e1-3229-4c7a-a1b8-8c1267dc13ed.png)
This is the rofi view of $brightnessctl get -P:
![2022-09-10-223015_1366x768_scrot](https://user-images.githubusercontent.com/108534456/189491620-b809a352-4a18-4fbe-95d2-091626a8f087.png)
This is the rofi display of $brightnessctl get (without -P), the output is visible even though it's not in percent form:
![2022-09-10-223053_1366x768_scrot](https://user-images.githubusercontent.com/108534456/189491738-05aaada7-b5df-4582-a8ac-9d2f9dabab88.png)

**Desktop (please complete the following information):**
Archcraft

**Additional context**
Looks like Brightnessctl doesn't have support for displaying output percentage, issue is discussed here: https://github.com/Hummer12007/brightnessctl/issues/55

**Comment by ferroson** [comment] 2022-09-10 16:26
I changed the 47th line to:
BRIGHTNESS="$(brightnessctl ${BRIGHTNESS_DEVICE:+-d "$BRIGHTNESS_DEVICE"} -m | awk -F, '{print substr($4, 0, length($4)-1)}')"
and the result is shown as a percent
![2022-09-10-232122_1366x768_scrot](https://user-images.githubusercontent.com/108534456/189492568-e2893748-355f-467b-882d-4067599b0ec4.png)

**Comment by owl4ce** [comment] 2022-09-10 18:47
Hmm ..., there's something strange. I knew this was on my first dotfiles configuration, but then just found out that `brightnessctl` can format the output to percent via `-P` option.

Consider using only built-in shell features rather than external programs like `awk` or `grep`. One of my script's consistency is to avoid `awk`, and use parameter expansion instead.

**Comment by owl4ce** [comment] 2022-09-10 18:51
The `brightnessctl` issue itself was closed as completed in https://github.com/Hummer12007/brightnessctl/commit/9a1af7e6931b61f215782174e6cdb74cde54b44f.

**Comment by ferroson** [comment] 2022-09-10 23:11
> The `brightnessctl` issue itself was closed as completed in [Hummer12007/brightnessctl@9a1af7e](https://github.com/Hummer12007/brightnessctl/commit/9a1af7e6931b61f215782174e6cdb74cde54b44f).

Maybe I'm using the old one (I didn't expect this to happen in Arch derivatives), as I thought the -P option is available in the git brightnessctl version (available in AUR)

First I checked the brightnessctl version installed from pacman (community), the build date is one year older than https://github.com/Hummer12007/brightnessctl/commit/9a1af7e6931b61f215782174e6cdb74cde54b44f :
  brightnessctl --version                                                                                                                                                         ~  
0.5
  pacman -Qi brightnessctl                                                                                                                                                        ~  
Name            : brightnessctl
Version         : 0.5.1-2
Description     : Lightweight brightness control tool
Architecture    : x86_64
URL             : https://github.com/Hummer12007/brightnessctl
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : systemd-libs
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 28,10 KiB
Packager        : Christian Rebischke <Chris.Rebischke@archlinux.org>
Build Date      : Sab 04 Apr 2020 06:56:45 
Install Date    : Kam 18 Agu 2022 02:53:59 
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

Then I install brightnessctl-git from AUR and check if the -P option exists, the answer is yes:
  brightnessctl --help                                                                                                                                                            ~  
brightnessctl 0.5 - read and control device brightness.

Usage: brightnessctl [options] [operation] [value]

Options:
  -l, --list                 	list devices with available brightness controls.
  -q, --quiet                	suppress output.
  -p, --pretend              	do not perform write operations.
  -m, --machine-readable     	produce machine-readable output.
  -P, --percentage           	display value as a percentage in get.
  -n, --min-value[=MIN-VALUE]	set minimum brightness (to 1 if MIN-VALUE is omitted).
  -e, --exponent[=K]         	changes percentage curve to exponential (to 4 if K is omitted).
  -s, --save                 	save previous state in a temporary file.
  -r, --restore              	restore previous saved state.
  -h, --help                 	print this help.
  -d, --device=DEVICE        	specify device name (can be a wildcard).
  -c, --class=CLASS          	specify device class.
  -V, --version              	print version and exit.

**Comment by ferroson** [comment] 2022-09-10 23:39
Edit: neither brightnessctl from pacman nor brightnessctl from AUR are at version 0.5, but the package following git's development has a new feature (in this case the -P option)

**Comment by owl4ce** [comment] 2022-09-11 00:34
If the problem is that the package depends on the version tag (which isn't updated from upstream) then I'll code it like `amixer`, using the expansion parameter. Need to be tested.

**Comment by owl4ce** [comment] 2022-09-11 00:41
@ferroson Can you test this?

```sh
BRIGHTNESS="$(brightnessctl ${BRIGHTNESS_DEVICE:+-d "$BRIGHTNESS_DEVICE"} info)" \
BRIGHTNESS="${BRIGHTNESS#*\ \(}" \
BRIGHTNESS="${BRIGHTNESS%%\%\)*}"
```

**Comment by owl4ce** [comment] 2022-09-11 01:17
<p align="center"><img alt="" src="https://user-images.githubusercontent.com/53987136/189507543-61798a45-8be1-4063-82b2-3763c75e2e8d.png"/></p>

**Comment by ferroson** [comment] 2022-09-11 01:18
@owl4ce Looks fine even with pacman version
![2022-09-11-081605_1366x768_scrot](https://user-images.githubusercontent.com/108534456/189507572-f312d6db-0f85-436d-a41e-e2ba514cad0a.png)

**Comment by owl4ce** [comment] 2022-09-11 01:20
**Nice.** I'll update the script for both.

```sh
On branch ng
Your branch is up to date with 'origin/ng'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .config/rofi/scripts/custom-modi/modi-media.sh
	modified:   .scripts/change-brightness.sh

no changes added to commit (use "git add" and/or "git commit -a")
```

Thank you for reporting the issue.

**Closed** 2022-09-11 01:32 UTC
Labels: invalid, wontfix
