### ISSUE TITLE
Can't shutdown/reboot/sleep [Bug]

### ISSUE THREAD

**Issue by inozura** [owl4ce/dotfiles#180] opened 2022-05-15 13:16 UTC
Hello there, thank you for sharing your pretty dotfiles
I have a issue which is really important.

When I'm trying to shutdown/reboot/sleep my computer don't do anything, which is still on.

I'm use ubuntu 22.04 with dell e7240 laptop

thank you

**Comment by owl4ce** [comment] 2022-05-15 13:23
Hello. Is there `loginctl` command on your Ubuntu?

I'm wondering, is it because it doesn't exist or requires root privileges which it shouldn't "not" need (also not sure if it needs a `polkit`).

**Comment by inozura** [comment] 2022-05-15 13:46
do I need to uncommand the killuserprocesses
![2022-05-15-204251_1920x1080_scrot](https://user-images.githubusercontent.com/64202802/168476110-5eb5fac6-b67b-4b8d-a9b5-0ccafec17227.png)
?

**Comment by owl4ce** [comment] 2022-05-15 13:49
As I see mine is **no**. I think it's not caused by `logind.conf`.

**Comment by owl4ce** [comment] 2022-05-15 13:56
```sh
$ man 5 logind.conf | less +/KillUserProcesses=
```

**Comment by owl4ce** [comment] 2022-05-15 13:59
However, how about trying it?

**Comment by owl4ce** [comment] 2022-05-15 14:06
Ah I see, it looks like **systemd**-based vs init-freedom issue. There's a little difference about `loginctl`(1) and `systemctl`(1). In init-freedom distro, the **poweroff**, **reboot**, and **suspend** commands are the part of `loginctl`, but the original systemd-logind implement it in the `systemctl` which doesn't exist in init-freedom Linux distributions (elogind).

Thanks for reporting the issue!

**Comment by owl4ce** [comment] 2022-05-15 14:47
Hi @inozura, can you try the `systemctl` command followed by these arguments (excluding `loginctl`) to indicate the `systemctl` works as expected. I'm currently wondering about the new `systemctl` [replacement](https://github.com/gdraheim/docker-systemctl-replacement) in Ubuntu (since 21.04), the manpage doesn't explain about commands e.g reboot, etc. So, I was able to fix, merge commits, and close this issue. Thank you.

https://github.com/owl4ce/dotfiles/blob/196a00cf4dc0b67ebe7fa104aa1031e77203e708/.config/rofi/scripts/custom-modi/modi-session.sh#L59

**Closed** 2022-05-15 15:40 UTC
Labels: bug, invalid, wontfix
